apiVersion: v1
kind: Service
metadata:
  labels:
    app: neko
  name: neko-lb
  namespace: jeancossio
spec:
  ports:
  - name: neko-port-80
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: neko-port-56000
    port: 56000
    protocol: UDP
    targetPort: 56000
  - name: neko-port-56001
    port: 56001
    protocol: UDP
    targetPort: 56001
  - name: neko-port-56002
    port: 56002
    protocol: UDP
    targetPort: 56002
  - name: neko-port-56003
    port: 56003
    protocol: UDP
    targetPort: 56003
  - name: neko-port-56004
    port: 56004
    protocol: UDP
    targetPort: 56004
  - name: neko-port-56005
    port: 56005
    protocol: UDP
    targetPort: 56005
  - name: neko-port-56006
    port: 56006
    protocol: UDP
    targetPort: 56006
  - name: neko-port-56007
    port: 56007
    protocol: UDP
    targetPort: 56007
  - name: neko-port-56008
    port: 56008
    protocol: UDP
    targetPort: 56008
  - name: neko-port-56009
    port: 56009
    protocol: UDP
    targetPort: 56009
  - name: neko-port-56010
    port: 56010
    protocol: UDP
    targetPort: 56010
  - name: neko-port-56011
    port: 56011
    protocol: UDP
    targetPort: 56011
  - name: neko-port-56012
    port: 56012
    protocol: UDP
    targetPort: 56012
  - name: neko-port-56013
    port: 56013
    protocol: UDP
    targetPort: 56013
  - name: neko-port-56014
    port: 56014
    protocol: UDP
    targetPort: 56014
  - name: neko-port-56015
    port: 56015
    protocol: UDP
    targetPort: 56015
  - name: neko-port-56016
    port: 56016
    protocol: UDP
    targetPort: 56016
  - name: neko-port-56017
    port: 56017
    protocol: UDP
    targetPort: 56017
  - name: neko-port-56018
    port: 56018
    protocol: UDP
    targetPort: 56018
  - name: neko-port-56019
    port: 56019
    protocol: UDP
    targetPort: 56019
  - name: neko-port-56020
    port: 56020
    protocol: UDP
    targetPort: 56020
  - name: neko-port-56021
    port: 56021
    protocol: UDP
    targetPort: 56021
  - name: neko-port-56022
    port: 56022
    protocol: UDP
    targetPort: 56022
  - name: neko-port-56023
    port: 56023
    protocol: UDP
    targetPort: 56023
  - name: neko-port-56024
    port: 56024
    protocol: UDP
    targetPort: 56024
  - name: neko-port-56025
    port: 56025
    protocol: UDP
    targetPort: 56025
  - name: neko-port-56026
    port: 56026
    protocol: UDP
    targetPort: 56026
  - name: neko-port-56027
    port: 56027
    protocol: UDP
    targetPort: 56027
  - name: neko-port-56028
    port: 56028
    protocol: UDP
    targetPort: 56028
  - name: neko-port-56029
    port: 56029
    protocol: UDP
    targetPort: 56029
  - name: neko-port-56030
    port: 56030
    protocol: UDP
    targetPort: 56030
  - name: neko-port-56031
    port: 56031
    protocol: UDP
    targetPort: 56031
  - name: neko-port-56032
    port: 56032
    protocol: UDP
    targetPort: 56032
  - name: neko-port-56033
    port: 56033
    protocol: UDP
    targetPort: 56033
  - name: neko-port-56034
    port: 56034
    protocol: UDP
    targetPort: 56034
  - name: neko-port-56035
    port: 56035
    protocol: UDP
    targetPort: 56035
  - name: neko-port-56036
    port: 56036
    protocol: UDP
    targetPort: 56036
  - name: neko-port-56037
    port: 56037
    protocol: UDP
    targetPort: 56037
  - name: neko-port-56038
    port: 56038
    protocol: UDP
    targetPort: 56038
  - name: neko-port-56039
    port: 56039
    protocol: UDP
    targetPort: 56039
  - name: neko-port-56040
    port: 56040
    protocol: UDP
    targetPort: 56040
  - name: neko-port-56041
    port: 56041
    protocol: UDP
    targetPort: 56041
  - name: neko-port-56042
    port: 56042
    protocol: UDP
    targetPort: 56042
  - name: neko-port-56043
    port: 56043
    protocol: UDP
    targetPort: 56043
  - name: neko-port-56044
    port: 56044
    protocol: UDP
    targetPort: 56044
  - name: neko-port-56045
    port: 56045
    protocol: UDP
    targetPort: 56045
  - name: neko-port-56046
    port: 56046
    protocol: UDP
    targetPort: 56046
  - name: neko-port-56047
    port: 56047
    protocol: UDP
    targetPort: 56047
  - name: neko-port-56048
    port: 56048
    protocol: UDP
    targetPort: 56048
  - name: neko-port-56049
    port: 56049
    protocol: UDP
    targetPort: 56049
  - name: neko-port-56050
    port: 56050
    protocol: UDP
    targetPort: 56050
  - name: neko-port-56051
    port: 56051
    protocol: UDP
    targetPort: 56051
  - name: neko-port-56052
    port: 56052
    protocol: UDP
    targetPort: 56052
  - name: neko-port-56053
    port: 56053
    protocol: UDP
    targetPort: 56053
  - name: neko-port-56054
    port: 56054
    protocol: UDP
    targetPort: 56054
  - name: neko-port-56055
    port: 56055
    protocol: UDP
    targetPort: 56055
  - name: neko-port-56056
    port: 56056
    protocol: UDP
    targetPort: 56056
  - name: neko-port-56057
    port: 56057
    protocol: UDP
    targetPort: 56057
  - name: neko-port-56058
    port: 56058
    protocol: UDP
    targetPort: 56058
  - name: neko-port-56059
    port: 56059
    protocol: UDP
    targetPort: 56059
  - name: neko-port-56060
    port: 56060
    protocol: UDP
    targetPort: 56060
  - name: neko-port-56061
    port: 56061
    protocol: UDP
    targetPort: 56061
  - name: neko-port-56062
    port: 56062
    protocol: UDP
    targetPort: 56062
  - name: neko-port-56063
    port: 56063
    protocol: UDP
    targetPort: 56063
  - name: neko-port-56064
    port: 56064
    protocol: UDP
    targetPort: 56064
  - name: neko-port-56065
    port: 56065
    protocol: UDP
    targetPort: 56065
  - name: neko-port-56066
    port: 56066
    protocol: UDP
    targetPort: 56066
  - name: neko-port-56067
    port: 56067
    protocol: UDP
    targetPort: 56067
  - name: neko-port-56068
    port: 56068
    protocol: UDP
    targetPort: 56068
  - name: neko-port-56069
    port: 56069
    protocol: UDP
    targetPort: 56069
  - name: neko-port-56070
    port: 56070
    protocol: UDP
    targetPort: 56070
  - name: neko-port-56071
    port: 56071
    protocol: UDP
    targetPort: 56071
  - name: neko-port-56072
    port: 56072
    protocol: UDP
    targetPort: 56072
  - name: neko-port-56073
    port: 56073
    protocol: UDP
    targetPort: 56073
  - name: neko-port-56074
    port: 56074
    protocol: UDP
    targetPort: 56074
  - name: neko-port-56075
    port: 56075
    protocol: UDP
    targetPort: 56075
  - name: neko-port-56076
    port: 56076
    protocol: UDP
    targetPort: 56076
  - name: neko-port-56077
    port: 56077
    protocol: UDP
    targetPort: 56077
  - name: neko-port-56078
    port: 56078
    protocol: UDP
    targetPort: 56078
  - name: neko-port-56079
    port: 56079
    protocol: UDP
    targetPort: 56079
  - name: neko-port-56080
    port: 56080
    protocol: UDP
    targetPort: 56080
  - name: neko-port-56081
    port: 56081
    protocol: UDP
    targetPort: 56081
  - name: neko-port-56082
    port: 56082
    protocol: UDP
    targetPort: 56082
  - name: neko-port-56083
    port: 56083
    protocol: UDP
    targetPort: 56083
  - name: neko-port-56084
    port: 56084
    protocol: UDP
    targetPort: 56084
  - name: neko-port-56085
    port: 56085
    protocol: UDP
    targetPort: 56085
  - name: neko-port-56086
    port: 56086
    protocol: UDP
    targetPort: 56086
  - name: neko-port-56087
    port: 56087
    protocol: UDP
    targetPort: 56087
  - name: neko-port-56088
    port: 56088
    protocol: UDP
    targetPort: 56088
  - name: neko-port-56089
    port: 56089
    protocol: UDP
    targetPort: 56089
  - name: neko-port-56090
    port: 56090
    protocol: UDP
    targetPort: 56090
  - name: neko-port-56091
    port: 56091
    protocol: UDP
    targetPort: 56091
  - name: neko-port-56092
    port: 56092
    protocol: UDP
    targetPort: 56092
  - name: neko-port-56093
    port: 56093
    protocol: UDP
    targetPort: 56093
  - name: neko-port-56094
    port: 56094
    protocol: UDP
    targetPort: 56094
  - name: neko-port-56095
    port: 56095
    protocol: UDP
    targetPort: 56095
  - name: neko-port-56096
    port: 56096
    protocol: UDP
    targetPort: 56096
  - name: neko-port-56097
    port: 56097
    protocol: UDP
    targetPort: 56097
  - name: neko-port-56098
    port: 56098
    protocol: UDP
    targetPort: 56098
  - name: neko-port-56099
    port: 56099
    protocol: UDP
    targetPort: 56099
  - name: neko-port-56100
    port: 56100
    protocol: UDP
    targetPort: 56100
  selector:
    app: neko
  type: LoadBalancer
