apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackcandy
  name: blackcandy-lb
  namespace: jeancossio
spec:
  ports:
  - name: blackcandy-port
    port: 8018
    protocol: TCP
    targetPort: 80
  selector:
    app: blackcandy
  type: LoadBalancer
